language: python
python:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 || $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install -q coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 || $TRAVIS_PYTHON_VERSION == 3.3 ]]; then coverage run setup.py test; else python setup.py test; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ||  $TRAVIS_PYTHON_VERSION == 3.3 ]]; then coveralls; fi
